/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target records: `cluster_memory` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedLlvmFacts, GeneratedPtxVersion, GeneratedSelectionAlternative,
    GeneratedSelectionConstraints, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[
    GeneratedIntrinsicTarget {
        marker: "v1:i0320",
        id: "map_shared_rank",
        abi_id: "i0320",
        dialect_op: "nvvm.mapa_shared_cluster",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[
            GeneratedSelectionAlternative {
                source_record: "mapa_shared_cluster_64",
                asm: "mapa.shared::cluster.u64 \t$d, $a, $b;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 90",
                    "Subtarget->getPTXVersion() >= 78",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
            GeneratedSelectionAlternative {
                source_record: "mapa_shared_cluster_64i",
                asm: "mapa.shared::cluster.u64 \t$d, $a, $b;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 90",
                    "Subtarget->getPTXVersion() >= 78",
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[],
                },
            },
        ],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoMem", "IntrSpeculatable", "NoCapture<arg0>"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0321",
        id: "dsmem_read_u32",
        abi_id: "i0321",
        dialect_op: "nvvm.dsmem_read_u32",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
];
