/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target records: `cluster_barrier` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedClusterBarrierMode, GeneratedHardwareAlternative,
    GeneratedHardwareTarget, GeneratedIntrinsicBackend, GeneratedIntrinsicTarget,
    GeneratedIntrinsicVariant, GeneratedLlvmFacts, GeneratedPtxVersion,
    GeneratedSelectionAlternative, GeneratedSelectionConstraints, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[
    GeneratedIntrinsicTarget {
        marker: "v1:i0277",
        id: "barrier_cluster_arrive",
        abi_id: "i0277",
        dialect_op: "nvvm.cluster_barrier",
        variant: GeneratedIntrinsicVariant::ClusterBarrier {
            mode: GeneratedClusterBarrierMode::Arrive,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "barrier_cluster_arrive",
            asm: "barrier.cluster.arrive;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0278",
        id: "barrier_cluster_arrive_aligned",
        abi_id: "i0278",
        dialect_op: "nvvm.cluster_barrier",
        variant: GeneratedIntrinsicVariant::ClusterBarrier {
            mode: GeneratedClusterBarrierMode::ArriveAligned,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "barrier_cluster_arrive_aligned",
            asm: "barrier.cluster.arrive.aligned;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0279",
        id: "barrier_cluster_arrive_relaxed",
        abi_id: "i0279",
        dialect_op: "nvvm.cluster_barrier",
        variant: GeneratedIntrinsicVariant::ClusterBarrier {
            mode: GeneratedClusterBarrierMode::ArriveRelaxed,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(80),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "barrier_cluster_arrive_relaxed",
            asm: "barrier.cluster.arrive.relaxed;",
            predicates: &[
                "Subtarget->getPTXVersion() >= 80",
                "Subtarget->getSmVersion() >= 90",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0280",
        id: "barrier_cluster_arrive_relaxed_aligned",
        abi_id: "i0280",
        dialect_op: "nvvm.cluster_barrier",
        variant: GeneratedIntrinsicVariant::ClusterBarrier {
            mode: GeneratedClusterBarrierMode::ArriveRelaxedAligned,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(80),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "barrier_cluster_arrive_relaxed_aligned",
            asm: "barrier.cluster.arrive.relaxed.aligned;",
            predicates: &[
                "Subtarget->getPTXVersion() >= 80",
                "Subtarget->getSmVersion() >= 90",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0281",
        id: "barrier_cluster_wait",
        abi_id: "i0281",
        dialect_op: "nvvm.cluster_barrier",
        variant: GeneratedIntrinsicVariant::ClusterBarrier {
            mode: GeneratedClusterBarrierMode::Wait,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "barrier_cluster_wait",
            asm: "barrier.cluster.wait;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0282",
        id: "barrier_cluster_wait_aligned",
        abi_id: "i0282",
        dialect_op: "nvvm.cluster_barrier",
        variant: GeneratedIntrinsicVariant::ClusterBarrier {
            mode: GeneratedClusterBarrierMode::WaitAligned,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "barrier_cluster_wait_aligned",
            asm: "barrier.cluster.wait.aligned;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
];
