/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target records: `movmatrix` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedPtxVersion, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[GeneratedIntrinsicTarget {
    marker: "v1:i0305",
    id: "movmatrix_trans_b16",
    abi_id: "i0305",
    dialect_op: "nvvm.movmatrix_trans_b16",
    variant: GeneratedIntrinsicVariant::Scalar,
    requirement: GeneratedTargetRequirement {
        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
        hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(75)]),
    },
    backend_requirements: &[
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LlvmNvptx,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(75),
                ]),
            },
        },
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LibNvvm,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(75),
                ]),
            },
        },
    ],
    selections: &[],
    llvm: None,
}];
