/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target records: `scalar_math` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedLlvmFacts, GeneratedPtxVersion, GeneratedSelectionAlternative,
    GeneratedSelectionConstraints, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[
    GeneratedIntrinsicTarget {
        marker: "v1:i0782",
        id: "sin_approx_f32",
        abi_id: "i0782",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0783",
        id: "sin_approx_ftz_f32",
        abi_id: "i0783",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0784",
        id: "cos_approx_f32",
        abi_id: "i0784",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0785",
        id: "cos_approx_ftz_f32",
        abi_id: "i0785",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0786",
        id: "lg2_approx_f32",
        abi_id: "i0786",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0787",
        id: "lg2_approx_ftz_f32",
        abi_id: "i0787",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0788",
        id: "rcp_approx_ftz_f32",
        abi_id: "i0788",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_APPROX_FTZ_F",
            asm: "rcp.approx.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0789",
        id: "rcp_rn_f32",
        abi_id: "i0789",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RN_F",
            asm: "rcp.rn.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0790",
        id: "rcp_rn_ftz_f32",
        abi_id: "i0790",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RN_FTZ_F",
            asm: "rcp.rn.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0791",
        id: "rcp_rz_f32",
        abi_id: "i0791",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RZ_F",
            asm: "rcp.rz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0792",
        id: "rcp_rz_ftz_f32",
        abi_id: "i0792",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RZ_FTZ_F",
            asm: "rcp.rz.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0793",
        id: "rcp_rm_f32",
        abi_id: "i0793",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RM_F",
            asm: "rcp.rm.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0794",
        id: "rcp_rm_ftz_f32",
        abi_id: "i0794",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RM_FTZ_F",
            asm: "rcp.rm.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0795",
        id: "rcp_rp_f32",
        abi_id: "i0795",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RP_F",
            asm: "rcp.rp.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0796",
        id: "rcp_rp_ftz_f32",
        abi_id: "i0796",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RP_FTZ_F",
            asm: "rcp.rp.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0797",
        id: "rcp_approx_ftz_f64",
        abi_id: "i0797",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_APPROX_FTZ_D",
            asm: "rcp.approx.ftz.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0798",
        id: "rcp_rn_f64",
        abi_id: "i0798",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RN_D",
            asm: "rcp.rn.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0799",
        id: "rcp_rz_f64",
        abi_id: "i0799",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RZ_D",
            asm: "rcp.rz.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0800",
        id: "rcp_rm_f64",
        abi_id: "i0800",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RM_D",
            asm: "rcp.rm.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0801",
        id: "rcp_rp_f64",
        abi_id: "i0801",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_RCP_RP_D",
            asm: "rcp.rp.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0802",
        id: "rsqrt_approx_f32",
        abi_id: "i0802",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0803",
        id: "rsqrt_approx_ftz_f32",
        abi_id: "i0803",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0804",
        id: "rsqrt_approx_f64",
        abi_id: "i0804",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0805",
        id: "sqrt_approx_f32",
        abi_id: "i0805",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_APPROX_F",
            asm: "sqrt.approx.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0806",
        id: "sqrt_approx_ftz_f32",
        abi_id: "i0806",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_APPROX_FTZ_F",
            asm: "sqrt.approx.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0807",
        id: "sqrt_rn_f32",
        abi_id: "i0807",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RN_F",
            asm: "sqrt.rn.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0808",
        id: "sqrt_rn_ftz_f32",
        abi_id: "i0808",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RN_FTZ_F",
            asm: "sqrt.rn.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0809",
        id: "sqrt_rz_f32",
        abi_id: "i0809",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RZ_F",
            asm: "sqrt.rz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0810",
        id: "sqrt_rz_ftz_f32",
        abi_id: "i0810",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RZ_FTZ_F",
            asm: "sqrt.rz.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0811",
        id: "sqrt_rm_f32",
        abi_id: "i0811",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RM_F",
            asm: "sqrt.rm.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0812",
        id: "sqrt_rm_ftz_f32",
        abi_id: "i0812",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RM_FTZ_F",
            asm: "sqrt.rm.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0813",
        id: "sqrt_rp_f32",
        abi_id: "i0813",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RP_F",
            asm: "sqrt.rp.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0814",
        id: "sqrt_rp_ftz_f32",
        abi_id: "i0814",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RP_FTZ_F",
            asm: "sqrt.rp.ftz.f32 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0815",
        id: "sqrt_rn_f64",
        abi_id: "i0815",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RN_D",
            asm: "sqrt.rn.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0816",
        id: "sqrt_rz_f64",
        abi_id: "i0816",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RZ_D",
            asm: "sqrt.rz.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0817",
        id: "sqrt_rm_f64",
        abi_id: "i0817",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RM_D",
            asm: "sqrt.rm.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0818",
        id: "sqrt_rp_f64",
        abi_id: "i0818",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_SQRT_RP_D",
            asm: "sqrt.rp.f64 \t$dst, $src0;",
            predicates: &[],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0819",
        id: "ex2_approx_f32",
        abi_id: "i0819",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0820",
        id: "ex2_approx_ftz_f32",
        abi_id: "i0820",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0821",
        id: "tanh_approx_f32",
        abi_id: "i0821",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1016",
        id: "ex2_approx_f16",
        abi_id: "i1016",
        dialect_op: "nvvm.scalar_math",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                75,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(75),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoMem"],
            result_no_undef: false,
            result_range: None,
        }),
    },
];
