/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target records: `scalar_conversion` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedLlvmFacts, GeneratedPtxVersion, GeneratedScalarConversionRounding,
    GeneratedScalarConversionSaturation, GeneratedSelectionAlternative,
    GeneratedSelectionConstraints, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[
    GeneratedIntrinsicTarget {
        marker: "v1:i0368",
        id: "cvt_rna_tf32_f32",
        abi_id: "i0368",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::NearestAway,
            saturation: GeneratedScalarConversionSaturation::None,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rna",
            asm: "cvt.rna.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0369",
        id: "cvt_rna_satfinite_tf32_f32",
        abi_id: "i0369",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::NearestAway,
            saturation: GeneratedScalarConversionSaturation::Satfinite,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(81),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rna_satf",
            asm: "cvt.rna.satfinite.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 81",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0370",
        id: "cvt_rn_tf32_f32",
        abi_id: "i0370",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::NearestEven,
            saturation: GeneratedScalarConversionSaturation::None,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rn",
            asm: "cvt.rn.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0371",
        id: "cvt_rn_relu_tf32_f32",
        abi_id: "i0371",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::NearestEven,
            saturation: GeneratedScalarConversionSaturation::Relu,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rn_relu",
            asm: "cvt.rn.relu.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0372",
        id: "cvt_rn_satfinite_tf32_f32",
        abi_id: "i0372",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::NearestEven,
            saturation: GeneratedScalarConversionSaturation::Satfinite,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(86),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                100,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rn_satf",
            asm: "cvt.rn.satfinite.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 100",
                "Subtarget->getPTXVersion() >= 86",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0373",
        id: "cvt_rn_relu_satfinite_tf32_f32",
        abi_id: "i0373",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::NearestEven,
            saturation: GeneratedScalarConversionSaturation::ReluSatfinite,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(86),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                100,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rn_relu_satf",
            asm: "cvt.rn.relu.satfinite.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 100",
                "Subtarget->getPTXVersion() >= 86",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0374",
        id: "cvt_rz_tf32_f32",
        abi_id: "i0374",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::TowardZero,
            saturation: GeneratedScalarConversionSaturation::None,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rz",
            asm: "cvt.rz.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0375",
        id: "cvt_rz_relu_tf32_f32",
        abi_id: "i0375",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::TowardZero,
            saturation: GeneratedScalarConversionSaturation::Relu,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(78),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                90,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(90),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rz_relu",
            asm: "cvt.rz.relu.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0376",
        id: "cvt_rz_satfinite_tf32_f32",
        abi_id: "i0376",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::TowardZero,
            saturation: GeneratedScalarConversionSaturation::Satfinite,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(86),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                100,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rz_satf",
            asm: "cvt.rz.satfinite.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 100",
                "Subtarget->getPTXVersion() >= 86",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0377",
        id: "cvt_rz_relu_satfinite_tf32_f32",
        abi_id: "i0377",
        dialect_op: "nvvm.scalar_conversion",
        variant: GeneratedIntrinsicVariant::ScalarConversion {
            rounding: GeneratedScalarConversionRounding::TowardZero,
            saturation: GeneratedScalarConversionSaturation::ReluSatfinite,
        },
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(86),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                100,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(100),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "CVT_to_tf32_rz_relu_satf",
            asm: "cvt.rz.relu.satfinite.tf32.f32 \t$dst, $src;",
            predicates: &[
                "Subtarget->getSmVersion() >= 100",
                "Subtarget->getPTXVersion() >= 86",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"],
            result_no_undef: false,
            result_range: None,
        }),
    },
];
