/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target tests: `clc` intrinsics.

use super::super::*;

#[test]
fn clc_try_cancel_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0322").unwrap();
    assert_eq!(target.id, "clc_try_cancel");
    assert_eq!(target.abi_id, "i0322");
    assert_eq!(target.dialect_op, "nvvm.clc_try_cancel");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(100)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CLUSTERLAUNCHCONTRL_TRY_CANCEL",
            asm: "clusterlaunchcontrol.try_cancel.async.shared::cta.mbarrier::complete_tx::bytes.b128 \t[$addr], [$mbar];",
            predicates: &[
                "Subtarget->getSmVersion() >= 100",
                "Subtarget->getPTXVersion() >= 86"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrArgMemOnly", "IntrHasSideEffects"] as &[&str]
    );
}

#[test]
fn clc_try_cancel_multicast_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0323").unwrap();
    assert_eq!(target.id, "clc_try_cancel_multicast");
    assert_eq!(target.abi_id, "i0323");
    assert_eq!(target.dialect_op, "nvvm.clc_try_cancel_multicast");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const {
            GeneratedHardwareTarget::AnyOf(&[
                GeneratedHardwareAlternative::ExactArchitecture(100),
                GeneratedHardwareAlternative::ExactArchitecture(101),
                GeneratedHardwareAlternative::ExactArchitecture(103),
                GeneratedHardwareAlternative::ExactArchitecture(110),
                GeneratedHardwareAlternative::ExactArchitecture(120),
                GeneratedHardwareAlternative::ExactArchitecture(121),
            ])
        }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::ExactArchitecture(100),
                            GeneratedHardwareAlternative::ExactArchitecture(101),
                            GeneratedHardwareAlternative::ExactArchitecture(103),
                            GeneratedHardwareAlternative::ExactArchitecture(110),
                            GeneratedHardwareAlternative::ExactArchitecture(120),
                            GeneratedHardwareAlternative::ExactArchitecture(121),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::ExactArchitecture(100),
                            GeneratedHardwareAlternative::ExactArchitecture(101),
                            GeneratedHardwareAlternative::ExactArchitecture(103),
                            GeneratedHardwareAlternative::ExactArchitecture(110),
                            GeneratedHardwareAlternative::ExactArchitecture(120),
                            GeneratedHardwareAlternative::ExactArchitecture(121),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CLUSTERLAUNCHCONTRL_TRY_CANCEL_MULTICAST",
            asm: "clusterlaunchcontrol.try_cancel.async.shared::cta.mbarrier::complete_tx::bytes.multicast::cluster::all.b128 \t[$addr], [$mbar];",
            predicates: &["Subtarget->hasClusterLaunchControlTryCancelMulticastSupport()"],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrArgMemOnly", "IntrHasSideEffects"] as &[&str]
    );
}

#[test]
fn clc_query_is_canceled_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0324").unwrap();
    assert_eq!(target.id, "clc_query_is_canceled");
    assert_eq!(target.abi_id, "i0324");
    assert_eq!(target.dialect_op, "nvvm.clc_query_is_canceled");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(100)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn clc_query_get_first_ctaid_x_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0325").unwrap();
    assert_eq!(target.id, "clc_query_get_first_ctaid_x");
    assert_eq!(target.abi_id, "i0325");
    assert_eq!(target.dialect_op, "nvvm.clc_query_get_first_ctaid_x");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(100)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn clc_query_get_first_ctaid_y_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0326").unwrap();
    assert_eq!(target.id, "clc_query_get_first_ctaid_y");
    assert_eq!(target.abi_id, "i0326");
    assert_eq!(target.dialect_op, "nvvm.clc_query_get_first_ctaid_y");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(100)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn clc_query_get_first_ctaid_z_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0327").unwrap();
    assert_eq!(target.id, "clc_query_get_first_ctaid_z");
    assert_eq!(target.abi_id, "i0327");
    assert_eq!(target.dialect_op, "nvvm.clc_query_get_first_ctaid_z");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(100)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(100),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}
