/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target tests: `cp_async` intrinsics.

use super::super::*;

#[test]
fn cp_async_ca_4_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0086").unwrap();
    assert_eq!(target.id, "cp_async_ca_4");
    assert_eq!(target.abi_id, "i0086");
    assert_eq!(target.dialect_op, "nvvm.cp_async_ca_4");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_CA_SHARED_GLOBAL_4",
            asm: "cp.async.ca.shared.global [$dst], [$src], 4;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_ca_zfill_4_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0087").unwrap();
    assert_eq!(target.id, "cp_async_ca_zfill_4");
    assert_eq!(target.abi_id, "i0087");
    assert_eq!(target.dialect_op, "nvvm.cp_async_ca_zfill_4");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CA_SHARED_GLOBAL_4_s",
                asm: "cp.async.ca.shared.global [$dst], [$src], 4, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CA_SHARED_GLOBAL_4_si",
                asm: "cp.async.ca.shared.global [$dst], [$src], 4, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_ca_8_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0088").unwrap();
    assert_eq!(target.id, "cp_async_ca_8");
    assert_eq!(target.abi_id, "i0088");
    assert_eq!(target.dialect_op, "nvvm.cp_async_ca_8");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_CA_SHARED_GLOBAL_8",
            asm: "cp.async.ca.shared.global [$dst], [$src], 8;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_ca_zfill_8_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0089").unwrap();
    assert_eq!(target.id, "cp_async_ca_zfill_8");
    assert_eq!(target.abi_id, "i0089");
    assert_eq!(target.dialect_op, "nvvm.cp_async_ca_zfill_8");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CA_SHARED_GLOBAL_8_s",
                asm: "cp.async.ca.shared.global [$dst], [$src], 8, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CA_SHARED_GLOBAL_8_si",
                asm: "cp.async.ca.shared.global [$dst], [$src], 8, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_ca_16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0090").unwrap();
    assert_eq!(target.id, "cp_async_ca_16");
    assert_eq!(target.abi_id, "i0090");
    assert_eq!(target.dialect_op, "nvvm.cp_async_ca_16");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_CA_SHARED_GLOBAL_16",
            asm: "cp.async.ca.shared.global [$dst], [$src], 16;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_ca_zfill_16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0091").unwrap();
    assert_eq!(target.id, "cp_async_ca_zfill_16");
    assert_eq!(target.abi_id, "i0091");
    assert_eq!(target.dialect_op, "nvvm.cp_async_ca_zfill_16");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CA_SHARED_GLOBAL_16_s",
                asm: "cp.async.ca.shared.global [$dst], [$src], 16, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CA_SHARED_GLOBAL_16_si",
                asm: "cp.async.ca.shared.global [$dst], [$src], 16, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_cg_16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0092").unwrap();
    assert_eq!(target.id, "cp_async_cg_16");
    assert_eq!(target.abi_id, "i0092");
    assert_eq!(target.dialect_op, "nvvm.cp_async_cg_16");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_CG_SHARED_GLOBAL_16",
            asm: "cp.async.cg.shared.global [$dst], [$src], 16;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_cg_zfill_16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0093").unwrap();
    assert_eq!(target.id, "cp_async_cg_zfill_16");
    assert_eq!(target.abi_id, "i0093");
    assert_eq!(target.dialect_op, "nvvm.cp_async_cg_zfill_16");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CG_SHARED_GLOBAL_16_s",
                asm: "cp.async.cg.shared.global [$dst], [$src], 16, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "CP_ASYNC_CG_SHARED_GLOBAL_16_si",
                asm: "cp.async.cg.shared.global [$dst], [$src], 16, $src_size;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 80",
                    "Subtarget->getPTXVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrNoCallback",
            "NoAlias<arg0>",
            "NoAlias<arg1>",
            "ReadOnly<arg1>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn cp_async_commit_group_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0094").unwrap();
    assert_eq!(target.id, "cp_async_commit_group");
    assert_eq!(target.abi_id, "i0094");
    assert_eq!(target.dialect_op, "nvvm.cp_async_commit_group");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_COMMIT_GROUP",
            asm: "cp.async.commit_group;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(target.llvm.unwrap().properties, &[] as &[&str]);
}

#[test]
fn cp_async_wait_all_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0095").unwrap();
    assert_eq!(target.id, "cp_async_wait_all");
    assert_eq!(target.abi_id, "i0095");
    assert_eq!(target.dialect_op, "nvvm.cp_async_wait_all");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_WAIT_ALL",
            asm: "cp.async.wait_all;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(target.llvm.unwrap().properties, &[] as &[&str]);
}

#[test]
fn cp_async_wait_group_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0096").unwrap();
    assert_eq!(target.id, "cp_async_wait_group");
    assert_eq!(target.abi_id, "i0096");
    assert_eq!(target.dialect_op, "nvvm.cp_async_wait_group");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_WAIT_GROUP",
            asm: "cp.async.wait_group \t$n;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["ImmArg<arg0>"] as &[&str]
    );
}

#[test]
fn cp_async_mbarrier_arrive_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0101").unwrap();
    assert_eq!(target.id, "cp_async_mbarrier_arrive");
    assert_eq!(target.abi_id, "i0101");
    assert_eq!(target.dialect_op, "nvvm.cp_async_mbarrier_arrive");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_MBARRIER_ARRIVE",
            asm: "cp.async.mbarrier.arrive.b64 \t[$addr];",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn cp_async_mbarrier_arrive_shared_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0102").unwrap();
    assert_eq!(target.id, "cp_async_mbarrier_arrive_shared");
    assert_eq!(target.abi_id, "i0102");
    assert_eq!(target.dialect_op, "nvvm.cp_async_mbarrier_arrive_shared");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_MBARRIER_ARRIVE_SHARED",
            asm: "cp.async.mbarrier.arrive.shared.b64 \t[$addr];",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn cp_async_mbarrier_arrive_noinc_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0103").unwrap();
    assert_eq!(target.id, "cp_async_mbarrier_arrive_noinc");
    assert_eq!(target.abi_id, "i0103");
    assert_eq!(target.dialect_op, "nvvm.cp_async_mbarrier_arrive_noinc");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_MBARRIER_ARRIVE_NOINC",
            asm: "cp.async.mbarrier.arrive.noinc.b64 \t[$addr];",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn cp_async_mbarrier_arrive_noinc_shared_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0104").unwrap();
    assert_eq!(target.id, "cp_async_mbarrier_arrive_noinc_shared");
    assert_eq!(target.abi_id, "i0104");
    assert_eq!(
        target.dialect_op,
        "nvvm.cp_async_mbarrier_arrive_noinc_shared"
    );
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "CP_ASYNC_MBARRIER_ARRIVE_NOINC_SHARED",
            asm: "cp.async.mbarrier.arrive.noinc.shared.b64 \t[$addr];",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}
