/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target tests: `execution_control` intrinsics.

use super::super::*;

#[test]
fn barrier_cta_sync_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0883").unwrap();
    assert_eq!(target.id, "barrier_cta_sync");
    assert_eq!(target.abi_id, "i0883");
    assert_eq!(target.dialect_op, "nvvm.barrier_cta_sync_count");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 60);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(30)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(30),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_ii",
                asm: "barrier.sync \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_ir",
                asm: "barrier.sync \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_ri",
                asm: "barrier.sync \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_rr",
                asm: "barrier.sync \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn barrier_cta_sync_aligned_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0884").unwrap();
    assert_eq!(target.id, "barrier_cta_sync_aligned");
    assert_eq!(target.abi_id, "i0884");
    assert_eq!(target.dialect_op, "nvvm.barrier_cta_sync_aligned_count");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 20);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(20)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(32),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(20),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(10),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_ALIGNED_ii",
                asm: "bar.sync \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_ALIGNED_ir",
                asm: "bar.sync \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_ALIGNED_ri",
                asm: "bar.sync \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_SYNC_ALIGNED_rr",
                asm: "bar.sync \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn barrier_cta_arrive_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0885").unwrap();
    assert_eq!(target.id, "barrier_cta_arrive");
    assert_eq!(target.abi_id, "i0885");
    assert_eq!(target.dialect_op, "nvvm.barrier_cta_arrive_count");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 60);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(30)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(30),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_ii",
                asm: "barrier.arrive \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_ir",
                asm: "barrier.arrive \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_ri",
                asm: "barrier.arrive \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_rr",
                asm: "barrier.arrive \t$i, $j;",
                predicates: &["Subtarget->getPTXVersion() >= 60"],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn barrier_cta_arrive_aligned_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0886").unwrap();
    assert_eq!(target.id, "barrier_cta_arrive_aligned");
    assert_eq!(target.abi_id, "i0886");
    assert_eq!(target.dialect_op, "nvvm.barrier_cta_arrive_aligned_count");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 20);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(20)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(32),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(20),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(10),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_ALIGNED_ii",
                asm: "bar.arrive \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_ALIGNED_ir",
                asm: "bar.arrive \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_ALIGNED_ri",
                asm: "bar.arrive \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "BARRIER_CTA_ARRIVE_ALIGNED_rr",
                asm: "bar.arrive \t$i, $j;",
                predicates: &[],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn grid_dependency_launch_dependents_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0913").unwrap();
    assert_eq!(target.id, "grid_dependency_launch_dependents");
    assert_eq!(target.abi_id, "i0913");
    assert_eq!(target.dialect_op, "nvvm.grid_dependency_launch_dependents");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "GRIDDEPCONTROL_LAUNCH_DEPENDENTS",
            asm: "griddepcontrol.launch_dependents;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrHasSideEffects", "IntrNoMem"] as &[&str]
    );
}

#[test]
fn grid_dependency_wait_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0914").unwrap();
    assert_eq!(target.id, "grid_dependency_wait");
    assert_eq!(target.abi_id, "i0914");
    assert_eq!(target.dialect_op, "nvvm.grid_dependency_wait");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "GRIDDEPCONTROL_WAIT",
            asm: "griddepcontrol.wait;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrHasSideEffects", "IntrNoMem"] as &[&str]
    );
}

#[test]
fn setmaxnreg_inc_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0915").unwrap();
    assert_eq!(target.id, "setmaxnreg_inc");
    assert_eq!(target.abi_id, "i0915");
    assert_eq!(target.dialect_op, "nvvm.setmaxnreg_inc");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const {
            GeneratedHardwareTarget::AnyOf(&[
                GeneratedHardwareAlternative::ExactArchitecture(100),
                GeneratedHardwareAlternative::FamilyTarget(100),
                GeneratedHardwareAlternative::ExactArchitecture(103),
                GeneratedHardwareAlternative::FamilyTarget(103),
                GeneratedHardwareAlternative::ExactArchitecture(110),
                GeneratedHardwareAlternative::FamilyTarget(110),
                GeneratedHardwareAlternative::ExactArchitecture(120),
                GeneratedHardwareAlternative::FamilyTarget(120),
                GeneratedHardwareAlternative::ExactArchitecture(121),
                GeneratedHardwareAlternative::FamilyTarget(121),
                GeneratedHardwareAlternative::ExactArchitecture(90),
            ])
        }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::ExactArchitecture(100),
                            GeneratedHardwareAlternative::FamilyTarget(100),
                            GeneratedHardwareAlternative::ExactArchitecture(103),
                            GeneratedHardwareAlternative::FamilyTarget(103),
                            GeneratedHardwareAlternative::ExactArchitecture(110),
                            GeneratedHardwareAlternative::FamilyTarget(110),
                            GeneratedHardwareAlternative::ExactArchitecture(120),
                            GeneratedHardwareAlternative::FamilyTarget(120),
                            GeneratedHardwareAlternative::ExactArchitecture(121),
                            GeneratedHardwareAlternative::FamilyTarget(121),
                            GeneratedHardwareAlternative::ExactArchitecture(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::ExactArchitecture(100),
                            GeneratedHardwareAlternative::FamilyTarget(100),
                            GeneratedHardwareAlternative::ExactArchitecture(103),
                            GeneratedHardwareAlternative::FamilyTarget(103),
                            GeneratedHardwareAlternative::ExactArchitecture(110),
                            GeneratedHardwareAlternative::FamilyTarget(110),
                            GeneratedHardwareAlternative::ExactArchitecture(120),
                            GeneratedHardwareAlternative::FamilyTarget(120),
                            GeneratedHardwareAlternative::ExactArchitecture(121),
                            GeneratedHardwareAlternative::FamilyTarget(121),
                            GeneratedHardwareAlternative::ExactArchitecture(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "anonymous_21745",
            asm: "setmaxnreg.inc.sync.aligned.u32 \t$reg_count;",
            predicates: &["Subtarget->hasSetMaxNRegSupport()"],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "ImmArg<arg0>",
            "IntrConvergent",
            "IntrHasSideEffects",
            "IntrNoMem",
            "Range<arg0,24,257>"
        ] as &[&str]
    );
}

#[test]
fn setmaxnreg_dec_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0916").unwrap();
    assert_eq!(target.id, "setmaxnreg_dec");
    assert_eq!(target.abi_id, "i0916");
    assert_eq!(target.dialect_op, "nvvm.setmaxnreg_dec");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const {
            GeneratedHardwareTarget::AnyOf(&[
                GeneratedHardwareAlternative::ExactArchitecture(100),
                GeneratedHardwareAlternative::FamilyTarget(100),
                GeneratedHardwareAlternative::ExactArchitecture(103),
                GeneratedHardwareAlternative::FamilyTarget(103),
                GeneratedHardwareAlternative::ExactArchitecture(110),
                GeneratedHardwareAlternative::FamilyTarget(110),
                GeneratedHardwareAlternative::ExactArchitecture(120),
                GeneratedHardwareAlternative::FamilyTarget(120),
                GeneratedHardwareAlternative::ExactArchitecture(121),
                GeneratedHardwareAlternative::FamilyTarget(121),
                GeneratedHardwareAlternative::ExactArchitecture(90),
            ])
        }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::ExactArchitecture(100),
                            GeneratedHardwareAlternative::FamilyTarget(100),
                            GeneratedHardwareAlternative::ExactArchitecture(103),
                            GeneratedHardwareAlternative::FamilyTarget(103),
                            GeneratedHardwareAlternative::ExactArchitecture(110),
                            GeneratedHardwareAlternative::FamilyTarget(110),
                            GeneratedHardwareAlternative::ExactArchitecture(120),
                            GeneratedHardwareAlternative::FamilyTarget(120),
                            GeneratedHardwareAlternative::ExactArchitecture(121),
                            GeneratedHardwareAlternative::FamilyTarget(121),
                            GeneratedHardwareAlternative::ExactArchitecture(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::ExactArchitecture(100),
                            GeneratedHardwareAlternative::FamilyTarget(100),
                            GeneratedHardwareAlternative::ExactArchitecture(103),
                            GeneratedHardwareAlternative::FamilyTarget(103),
                            GeneratedHardwareAlternative::ExactArchitecture(110),
                            GeneratedHardwareAlternative::FamilyTarget(110),
                            GeneratedHardwareAlternative::ExactArchitecture(120),
                            GeneratedHardwareAlternative::FamilyTarget(120),
                            GeneratedHardwareAlternative::ExactArchitecture(121),
                            GeneratedHardwareAlternative::FamilyTarget(121),
                            GeneratedHardwareAlternative::ExactArchitecture(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "anonymous_21747",
            asm: "setmaxnreg.dec.sync.aligned.u32 \t$reg_count;",
            predicates: &["Subtarget->hasSetMaxNRegSupport()"],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "ImmArg<arg0>",
            "IntrConvergent",
            "IntrHasSideEffects",
            "IntrNoMem",
            "Range<arg0,24,257>"
        ] as &[&str]
    );
}
