/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target tests: `mbarrier_extended` intrinsics.

use super::super::*;

#[test]
fn mbarrier_arrive_expect_tx_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0306").unwrap();
    assert_eq!(target.id, "mbarrier_arrive_expect_tx");
    assert_eq!(target.abi_id, "i0306");
    assert_eq!(target.dialect_op, "nvvm.mbarrier_arrive_expect_tx_shared");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn mbarrier_arrive_expect_tx_cluster_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0307").unwrap();
    assert_eq!(target.id, "mbarrier_arrive_expect_tx_cluster");
    assert_eq!(target.abi_id, "i0307");
    assert_eq!(target.dialect_op, "nvvm.mbarrier_arrive_expect_tx_cluster");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrArgMemOnly", "IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}

#[test]
fn mbarrier_arrive_cluster_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0308").unwrap();
    assert_eq!(target.id, "mbarrier_arrive_cluster");
    assert_eq!(target.abi_id, "i0308");
    assert_eq!(target.dialect_op, "nvvm.mbarrier_arrive_cluster");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert!(target.llvm.is_none());
}

#[test]
fn mbarrier_try_wait_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0309").unwrap();
    assert_eq!(target.id, "mbarrier_try_wait");
    assert_eq!(target.abi_id, "i0309");
    assert_eq!(target.dialect_op, "nvvm.mbarrier_try_wait_shared");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "mbar_try_wait_scope_cta_acquire_STATE",
            asm: "mbarrier.try_wait.shared.b64 $res, [$addr], $state;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 78"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback", "NoCapture<arg0>"] as &[&str]
    );
}

#[test]
fn mbarrier_try_wait_parity_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0310").unwrap();
    assert_eq!(target.id, "mbarrier_try_wait_parity");
    assert_eq!(target.abi_id, "i0310");
    assert_eq!(target.dialect_op, "nvvm.mbarrier_try_wait_parity_shared");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback", "NoCapture<arg0>"] as &[&str]
    );
}

#[test]
fn mbarrier_try_wait_parity_cluster_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0311").unwrap();
    assert_eq!(target.id, "mbarrier_try_wait_parity_cluster");
    assert_eq!(target.abi_id, "i0311");
    assert_eq!(target.dialect_op, "nvvm.mbarrier_try_wait_parity_cluster");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback", "NoCapture<arg0>"] as &[&str]
    );
}

#[test]
fn fence_proxy_async_shared_cta_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0312").unwrap();
    assert_eq!(target.id, "fence_proxy_async_shared_cta");
    assert_eq!(target.abi_id, "i0312");
    assert_eq!(target.dialect_op, "nvvm.fence_proxy_async_shared_cta");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "anonymous_14441",
            asm: "fence.proxy.async.shared::cta;",
            predicates: &[
                "Subtarget->getPTXVersion() >= 80",
                "Subtarget->getSmVersion() >= 90"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCallback"] as &[&str]
    );
}

#[test]
fn fence_mbarrier_init_release_cluster_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0313").unwrap();
    assert_eq!(target.id, "fence_mbarrier_init_release_cluster");
    assert_eq!(target.abi_id, "i0313");
    assert_eq!(
        target.dialect_op,
        "nvvm.fence_mbarrier_init_release_cluster"
    );
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "INT_FENCE_MBARRIER_INIT_RELEASE_CLUSTER",
            asm: "fence.mbarrier_init.release.cluster;",
            predicates: &[
                "Subtarget->getPTXVersion() >= 80",
                "Subtarget->getSmVersion() >= 90"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCallback"] as &[&str]
    );
}

#[test]
fn fence_proxy_async_generic_release_shared_cta_cluster_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0314").unwrap();
    assert_eq!(
        target.id,
        "fence_proxy_async_generic_release_shared_cta_cluster"
    );
    assert_eq!(target.abi_id, "i0314");
    assert_eq!(
        target.dialect_op,
        "nvvm.fence_proxy_async_generic_release_shared_cta_cluster"
    );
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_FENCE_PROXY_ASYNC_GENERIC_RELEASE_SYNC_RESTRICT_SPACE_CTA_SCOPE_CLUSTER",
            asm: "fence.proxy.async::generic.release.sync_restrict::shared::cta.cluster;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 86"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCallback"] as &[&str]
    );
}

#[test]
fn fence_proxy_async_generic_acquire_shared_cluster_cluster_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0315").unwrap();
    assert_eq!(
        target.id,
        "fence_proxy_async_generic_acquire_shared_cluster_cluster"
    );
    assert_eq!(target.abi_id, "i0315");
    assert_eq!(
        target.dialect_op,
        "nvvm.fence_proxy_async_generic_acquire_shared_cluster_cluster"
    );
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 86);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(86),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[GeneratedSelectionAlternative {
            source_record: "INT_NVVM_FENCE_PROXY_ASYNC_GENERIC_ACQUIRE_SYNC_RESTRICT_SPACE_CLUSTER_SCOPE_CLUSTER",
            asm: "fence.proxy.async::generic.acquire.sync_restrict::shared::cluster.cluster;",
            predicates: &[
                "Subtarget->getSmVersion() >= 90",
                "Subtarget->getPTXVersion() >= 86"
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[]
            }
        },]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCallback"] as &[&str]
    );
}

#[test]
fn nanosleep_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0316").unwrap();
    assert_eq!(target.id, "nanosleep");
    assert_eq!(target.abi_id, "i0316");
    assert_eq!(target.dialect_op, "nvvm.nanosleep");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 63);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(70)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(63),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(70),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(63),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "INT_NVVM_NANOSLEEP_I",
                asm: "nanosleep.u32 \t$i;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 70",
                    "Subtarget->getPTXVersion() >= 63"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "INT_NVVM_NANOSLEEP_R",
                asm: "nanosleep.u32 \t$i;",
                predicates: &[
                    "Subtarget->getSmVersion() >= 70",
                    "Subtarget->getPTXVersion() >= 63"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrHasSideEffects", "IntrNoMem"] as &[&str]
    );
}
