/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target tests: `packed_conversion` intrinsics.

use super::super::*;

#[test]
fn cvt_f32x2_bf16x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0071").unwrap();
    assert_eq!(target.id, "cvt_f32x2_bf16x2");
    assert_eq!(target.abi_id, "i0071");
    assert_eq!(target.dialect_op, "nvvm.cvt_f32x2_bf16x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_f16x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0081").unwrap();
    assert_eq!(target.id, "cvt_f16x2_f32");
    assert_eq!(target.abi_id, "i0081");
    assert_eq!(target.dialect_op, "nvvm.cvt_f16x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rz_f16x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0082").unwrap();
    assert_eq!(target.id, "cvt_rz_f16x2_f32");
    assert_eq!(target.abi_id, "i0082");
    assert_eq!(target.dialect_op, "nvvm.cvt_rz_f16x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_relu_f16x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0083").unwrap();
    assert_eq!(target.id, "cvt_rn_relu_f16x2_f32");
    assert_eq!(target.abi_id, "i0083");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_relu_f16x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_relu_bf16x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0084").unwrap();
    assert_eq!(target.id, "cvt_rn_relu_bf16x2_f32");
    assert_eq!(target.abi_id, "i0084");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_relu_bf16x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rz_bf16x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0085").unwrap();
    assert_eq!(target.id, "cvt_rz_bf16x2_f32");
    assert_eq!(target.abi_id, "i0085");
    assert_eq!(target.dialect_op, "nvvm.cvt_rz_bf16x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 70);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(80)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(80),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_e4m3x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0259").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_e4m3x2_f32");
    assert_eq!(target.abi_id, "i0259");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_e4m3x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_relu_e4m3x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0260").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_relu_e4m3x2_f32");
    assert_eq!(target.abi_id, "i0260");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_relu_e4m3x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_e5m2x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0261").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_e5m2x2_f32");
    assert_eq!(target.abi_id, "i0261");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_e5m2x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_relu_e5m2x2_f32_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0262").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_relu_e5m2x2_f32");
    assert_eq!(target.abi_id, "i0262");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_relu_e5m2x2_f32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_e4m3x2_f16x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0822").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_e4m3x2_f16x2");
    assert_eq!(target.abi_id, "i0822");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_e4m3x2_f16x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_relu_e4m3x2_f16x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0823").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_relu_e4m3x2_f16x2");
    assert_eq!(target.abi_id, "i0823");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_relu_e4m3x2_f16x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_e5m2x2_f16x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0824").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_e5m2x2_f16x2");
    assert_eq!(target.abi_id, "i0824");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_e5m2x2_f16x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_satfinite_relu_e5m2x2_f16x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0825").unwrap();
    assert_eq!(target.id, "cvt_rn_satfinite_relu_e5m2x2_f16x2");
    assert_eq!(target.abi_id, "i0825");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_satfinite_relu_e5m2x2_f16x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_f16x2_e4m3x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0826").unwrap();
    assert_eq!(target.id, "cvt_rn_f16x2_e4m3x2");
    assert_eq!(target.abi_id, "i0826");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_f16x2_e4m3x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_relu_f16x2_e4m3x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0827").unwrap();
    assert_eq!(target.id, "cvt_rn_relu_f16x2_e4m3x2");
    assert_eq!(target.abi_id, "i0827");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_relu_f16x2_e4m3x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_f16x2_e5m2x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0828").unwrap();
    assert_eq!(target.id, "cvt_rn_f16x2_e5m2x2");
    assert_eq!(target.abi_id, "i0828");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_f16x2_e5m2x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}

#[test]
fn cvt_rn_relu_f16x2_e5m2x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0829").unwrap();
    assert_eq!(target.id, "cvt_rn_relu_f16x2_e5m2x2");
    assert_eq!(target.abi_id, "i0829");
    assert_eq!(target.dialect_op, "nvvm.cvt_rn_relu_f16x2_e5m2x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 81);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(89)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(81),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(89),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrNoCreateUndefOrPoison", "IntrNoMem", "IntrSpeculatable"] as &[&str]
    );
}
