/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target tests: `warp_match` intrinsics.

use super::super::*;

#[test]
fn match_any_sync_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0045").unwrap();
    assert_eq!(target.id, "match_any_sync");
    assert_eq!(target.abi_id, "i0045");
    assert_eq!(target.dialect_op, "nvvm.match_any_sync_i32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 60);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(70)]) }
    );
    assert_eq!(target.backend_requirements, const { &[] });
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_32ii",
                asm: "match.any.sync.b32 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_32ir",
                asm: "match.any.sync.b32 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_32ri",
                asm: "match.any.sync.b32 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_32rr",
                asm: "match.any.sync.b32 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrConvergent",
            "IntrInaccessibleMemOnly",
            "IntrNoCallback"
        ] as &[&str]
    );
}

#[test]
fn match_any_i64_sync_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0046").unwrap();
    assert_eq!(target.id, "match_any_i64_sync");
    assert_eq!(target.abi_id, "i0046");
    assert_eq!(target.dialect_op, "nvvm.match_any_sync_i64");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 60);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(70)]) }
    );
    assert_eq!(target.backend_requirements, const { &[] });
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_64ii",
                asm: "match.any.sync.b64 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_64ir",
                asm: "match.any.sync.b64 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_64ri",
                asm: "match.any.sync.b64 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ANY_SYNC_64rr",
                asm: "match.any.sync.b64 \t$dest, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrConvergent",
            "IntrInaccessibleMemOnly",
            "IntrNoCallback"
        ] as &[&str]
    );
}

#[test]
fn match_all_sync_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0047").unwrap();
    assert_eq!(target.id, "match_all_sync");
    assert_eq!(target.abi_id, "i0047");
    assert_eq!(target.dialect_op, "nvvm.match_all_sync_i32");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 60);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(70)]) }
    );
    assert_eq!(target.backend_requirements, const { &[] });
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_32ii",
                asm: "match.all.sync.b32 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_32ir",
                asm: "match.all.sync.b32 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_32ri",
                asm: "match.all.sync.b32 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_32rr",
                asm: "match.all.sync.b32 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrConvergent",
            "IntrInaccessibleMemOnly",
            "IntrNoCallback"
        ] as &[&str]
    );
}

#[test]
fn match_all_i64_sync_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0048").unwrap();
    assert_eq!(target.id, "match_all_i64_sync");
    assert_eq!(target.abi_id, "i0048");
    assert_eq!(target.dialect_op, "nvvm.match_all_sync_i64");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 60);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(70)]) }
    );
    assert_eq!(target.backend_requirements, const { &[] });
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_64ii",
                asm: "match.all.sync.b64 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_64ir",
                asm: "match.all.sync.b64 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_64ri",
                asm: "match.all.sync.b64 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "MATCH_ALLP_SYNC_64rr",
                asm: "match.all.sync.b64 \t$dest|$pred, $value, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 70"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrConvergent",
            "IntrInaccessibleMemOnly",
            "IntrNoCallback"
        ] as &[&str]
    );
}
