/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target tests: `warp_barrier` intrinsics.

use super::super::*;

#[test]
fn sync_mask_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0049").unwrap();
    assert_eq!(target.id, "sync_mask");
    assert_eq!(target.abi_id, "i0049");
    assert_eq!(target.dialect_op, "nvvm.bar_warp_sync");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 60);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(30)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(30),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(60),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "INT_BAR_WARP_SYNC_I",
                asm: "bar.warp.sync \t$i;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "INT_BAR_WARP_SYNC_R",
                asm: "bar.warp.sync \t$i;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 60",
                    "Subtarget->getSmVersion() >= 30"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrNoCallback"] as &[&str]
    );
}
