/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! GPU intrinsic conversion: `dialect-nvvm` → LLVM dialect.
//!
//! This module converts `dialect-nvvm` (NVIDIA Virtual Machine) operations
//! to LLVM dialect ops, using either LLVM NVVM intrinsics or inline PTX
//! assembly depending on the operation.
//!
//! # Lowering Strategies
//!
//! ## Strategy 1: LLVM NVVM Intrinsics
//!
//! For well-supported operations, we call LLVM NVVM intrinsics:
//!
//! ```text
//! nvvm.read_tid_x  →  call i32 @llvm_nvvm_read_ptx_sreg_tid_x()
//! ```
//!
//! This is preferred when available because:
//! - LLVM can optimize the intrinsic
//! - Better debugging information
//! - Portable across LLVM versions
//!
//! ## Strategy 2: Inline PTX Assembly
//!
//! For complex or new operations without LLVM intrinsics, we use inline PTX:
//!
//! ```text
//! wgmma.fence  →  call void asm sideeffect convergent "wgmma.fence.sync.aligned;"
//! ```
//!
//! This is necessary for:
//! - Operations introduced after the LLVM NVVM intrinsics were designed
//! - Operations requiring specific PTX encoding
//! - Performance-critical paths where exact PTX is needed
//!
//! ## The `convergent` Attribute
//!
//! Warp-synchronous operations **must** use the `convergent` attribute on inline
//! assembly. This prevents LLVM from:
//! - Moving the operation across divergent control flow
//! - Speculating the operation
//! - Duplicating the operation
//!
//! Without `convergent`, operations like warp shuffle could be hoisted out of
//! conditionals, breaking the warp-synchronous semantics and causing hangs.
//!
//! # Module Organization
//!
//! Everything `intrinsics/catalog.json` describes is lowered by
//! `convert/generated_intrinsics/` -- beside this module, not inside it (it is
//! a private module, so this is a path rather than a link). What follows is the
//! hand-written converters, one row per file. Every module name in the table is
//! an intra-doc link on purpose: the docs gate runs under `-D warnings`, so a row
//! naming a module that no longer exists fails the build instead of going stale.
//!
//! Per-intrinsic PTX and minimum-SM requirements live in the catalog and are
//! rendered into `intrinsics/generated-reference.md`, so they are not restated
//! here.
//!
//! | Module                   | Purpose                                                                   |
//! |--------------------------|---------------------------------------------------------------------------|
//! | [`asm`]                  | User-authored inline PTX lowering                                         |
//! | [`atomic`]               | Atomic operation conversion: NVVM atomic dialect → LLVM atomic instructions|
//! | [`basic`]                | Basic NVVM intrinsic conversion for special registers                     |
//! | [`clc`]                  | Lower generated Cluster Launch Control operations through typed NVVM calls|
//! | [`cluster`]              | Compatibility lowering for derived cluster-grid values                    |
//! | [`common`]               | Common helpers for GPU intrinsic conversion                               |
//! | [`cp_async`]             | Lower generated classic `cp.async` operations through the selected backend|
//! | [`debug`]                | Debug and profiling intrinsic conversion                                  |
//! | [`dotprod`]              | Lower generated packed integer dot products through the selected backend  |
//! | [`execution_control`]    | Lowering for counted barriers, programmatic dependent launch, and register control|
//! | [`extended_minmax`]      | Lowering helper for generated extended min/max operations                 |
//! | [`integer_minmax`]       | Lowering helper for generated extended integer min/max operations         |
//! | [`ldmatrix`]             | Lower `ldmatrix` operations through the selected intrinsic backend        |
//! | [`mbarrier`]             | Mbarrier lowering for Ampere and newer GPUs                               |
//! | [`memory`]               | Memory address-space conversion intrinsics                                |
//! | [`packed`]               | Shared lowering helpers for generated packed arithmetic and conversions   |
//! | [`prmt`]                 | Lower generated byte permutations through the selected backend            |
//! | [`scalar_arithmetic`]    | Lowering helper for generated scalar floating-point arithmetic            |
//! | [`scalar_conversion`]    | Lowering helper for generated scalar conversions                          |
//! | [`scalar_math`]          | Lowering helper for generated unary scalar floating-point math            |
//! | [`tma`]                  | TMA conversion for Hopper and newer GPUs                                  |
//! | [`warp`]                 | Warp-level intrinsic conversion: shuffle and vote operations              |
//! | [`wgmma`]                | WGMMA conversion for Hopper `sm_90a`                                      |
//! | [`wmma`]                 | Shared lowering helpers for generated matrix intrinsics                   |
//!
//! # Adding New Intrinsics
//!
//! 1. Add the operation to `dialect-nvvm`
//! 2. Implement `MirToLlvmConversion` for the op in `convert/interface_impls.rs`
//! 3. Implement the conversion function in the appropriate module here
//! 4. Use `call_intrinsic` for LLVM intrinsics or `inline_asm_convergent` for PTX

pub mod asm;
pub mod atomic;
pub mod basic;
pub mod clc;
pub mod cluster;
pub mod common;
pub mod cp_async;
pub mod debug;
pub mod dotprod;
pub mod execution_control;
pub mod extended_minmax;
pub mod integer_minmax;
pub mod ldmatrix;
pub mod mbarrier;
pub mod memory;
pub mod packed;
pub mod prmt;
pub mod scalar_arithmetic;
pub mod scalar_conversion;
pub mod scalar_math;
pub mod tma;
pub mod warp;
pub mod wgmma;
pub mod wmma;
