; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.vote.ballot.sync(i32, i1)

define i32 @probe_ballot_sync(i32 %member_mask, i1 %predicate) {
  %result = call i32 @llvm.nvvm.vote.ballot.sync(i32 %member_mask, i1 %predicate)
  ret i32 %result
}
define i32 @probe_ballot_sync_immediate(i1 %predicate) {
  %result = call i32 @llvm.nvvm.vote.ballot.sync(i32 -1, i1 %predicate)
  ret i32 %result
}
