; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.ca.shared.global.4.s(ptr addrspace(3), ptr addrspace(1), i32)

define void @probe_cp_async_ca_zfill_4_register(ptr %shared_generic, ptr %global_generic, i32 %source_size) {
  %shared = addrspacecast ptr %shared_generic to ptr addrspace(3)
  %global = addrspacecast ptr %global_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.ca.shared.global.4.s(ptr addrspace(3) %shared, ptr addrspace(1) %global, i32 %source_size)
  ret void
}
define void @probe_cp_async_ca_zfill_4_immediate(ptr %shared_generic, ptr %global_generic) {
  %shared = addrspacecast ptr %shared_generic to ptr addrspace(3)
  %global = addrspacecast ptr %global_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.ca.shared.global.4.s(ptr addrspace(3) %shared, ptr addrspace(1) %global, i32 3)
  ret void
}
