; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.tensor.reduce.xor.im2col.5d(ptr addrspace(3), ptr, i32, i32, i32, i32, i32, i64, i1) #0

define void @probe_cp_async_bulk_tensor_reduce_xor_im2col_5d(ptr %src_generic, ptr %tensor_map, i32 %coord0, i32 %coord1, i32 %coord2, i32 %coord3, i32 %coord4) #0 {
  %src = addrspacecast ptr %src_generic to ptr addrspace(3)
  call void @llvm.nvvm.cp.async.bulk.tensor.reduce.xor.im2col.5d(ptr addrspace(3) %src, ptr %tensor_map, i32 %coord0, i32 %coord1, i32 %coord2, i32 %coord3, i32 %coord4, i64 0, i1 false) #0
  ret void
}

attributes #0 = { convergent }
