; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i16 @llvm.nvvm.ff.to.e4m3x2.rn(float, float)

define i16 @probe_cvt_rn_satfinite_e4m3x2_f32(float %low, float %high) {
  %result = call i16 @llvm.nvvm.ff.to.e4m3x2.rn(float %high, float %low)
  ret i16 %result
}
