; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define { i32, i1 } @probe_elect_sync_lib_nvvm_register(i32 %mask) #0 {
  %raw = call { i32, i32 } asm sideeffect "{ .reg .pred p; elect.sync $0|p, $2; selp.b32 $1, 1, 0, p; }", "=r,=r,r"(i32 %mask) #0
  %leader = extractvalue { i32, i32 } %raw, 0
  %predicate.i32 = extractvalue { i32, i32 } %raw, 1
  %predicate = trunc i32 %predicate.i32 to i1
  %result.0 = insertvalue { i32, i1 } poison, i32 %leader, 0
  %result.1 = insertvalue { i32, i1 } %result.0, i1 %predicate, 1
  ret { i32, i1 } %result.1
}
define { i32, i1 } @probe_elect_sync_lib_nvvm_constant_mask() #0 {
  %raw = call { i32, i32 } asm sideeffect "{ .reg .pred p; elect.sync $0|p, $2; selp.b32 $1, 1, 0, p; }", "=r,=r,r"(i32 -1) #0
  %leader = extractvalue { i32, i32 } %raw, 0
  %predicate.i32 = extractvalue { i32, i32 } %raw, 1
  %predicate = trunc i32 %predicate.i32 to i1
  %result.0 = insertvalue { i32, i1 } poison, i32 %leader, 0
  %result.1 = insertvalue { i32, i1 } %result.0, i1 %predicate, 1
  ret { i32, i1 } %result.1
}

attributes #0 = { convergent }
