; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.mma.ws.sp.tensor.zero_col_mask; route: inline PTX; source contract: TablegenSelectionChangesPtx
define void @probe_tcgen05_mma_ws_sp_tensor_zero_col_mask(i32 %d_tmem, i32 %a_tmem, i64 %b_desc, i32 %idesc, i1 %enable_d, i32 %metadata_tmem, i64 %zero_column_mask) #0 {
  call void asm sideeffect "{ .reg .pred %enable_pred; setp.ne.s32 %enable_pred, $4, 0; tcgen05.mma.ws.sp.cta_group::1.kind::f16.collector::b0::discard [$0], [$1], $2, [$5], $3, %enable_pred, $6; }", "r,r,l,r,r,r,l,~{memory}"(i32 %d_tmem, i32 %a_tmem, i64 %b_desc, i32 %idesc, i1 %enable_d, i32 %metadata_tmem, i64 %zero_column_mask) #0
  ret void
}

attributes #0 = { convergent }
