; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.st.16x64b.x64; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_st_16x64b_x64_raw(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7, i32 %d8, i32 %d9, i32 %d10, i32 %d11, i32 %d12, i32 %d13, i32 %d14, i32 %d15, i32 %d16, i32 %d17, i32 %d18, i32 %d19, i32 %d20, i32 %d21, i32 %d22, i32 %d23, i32 %d24, i32 %d25, i32 %d26, i32 %d27, i32 %d28, i32 %d29, i32 %d30, i32 %d31, i32 %d32, i32 %d33, i32 %d34, i32 %d35, i32 %d36, i32 %d37, i32 %d38, i32 %d39, i32 %d40, i32 %d41, i32 %d42, i32 %d43, i32 %d44, i32 %d45, i32 %d46, i32 %d47, i32 %d48, i32 %d49, i32 %d50, i32 %d51, i32 %d52, i32 %d53, i32 %d54, i32 %d55, i32 %d56, i32 %d57, i32 %d58, i32 %d59, i32 %d60, i32 %d61, i32 %d62, i32 %d63) #0 {
  call void asm sideeffect "tcgen05.st.sync.aligned.16x64b.x64.b32 [$0], {$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,$54,$55,$56,$57,$58,$59,$60,$61,$62,$63,$64};", "r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,~{memory}"(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7, i32 %d8, i32 %d9, i32 %d10, i32 %d11, i32 %d12, i32 %d13, i32 %d14, i32 %d15, i32 %d16, i32 %d17, i32 %d18, i32 %d19, i32 %d20, i32 %d21, i32 %d22, i32 %d23, i32 %d24, i32 %d25, i32 %d26, i32 %d27, i32 %d28, i32 %d29, i32 %d30, i32 %d31, i32 %d32, i32 %d33, i32 %d34, i32 %d35, i32 %d36, i32 %d37, i32 %d38, i32 %d39, i32 %d40, i32 %d41, i32 %d42, i32 %d43, i32 %d44, i32 %d45, i32 %d46, i32 %d47, i32 %d48, i32 %d49, i32 %d50, i32 %d51, i32 %d52, i32 %d53, i32 %d54, i32 %d55, i32 %d56, i32 %d57, i32 %d58, i32 %d59, i32 %d60, i32 %d61, i32 %d62, i32 %d63) #0
  ret void
}

attributes #0 = { convergent }
