; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.st.16x128b.x4; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_st_16x128b_x4_raw(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7) #0 {
  call void asm sideeffect "tcgen05.st.sync.aligned.16x128b.x4.b32 [$0], {$1,$2,$3,$4,$5,$6,$7,$8};", "r,r,r,r,r,r,r,r,r,~{memory}"(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7) #0
  ret void
}

attributes #0 = { convergent }
