; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.mma.shared.disable_output_lane.cg1; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_mma_f16(i32 %d, i64 %a, i64 %b, i32 %idesc, i1 %enable) #0 {
  call void asm sideeffect "{ .reg .pred %enable_pred; setp.ne.s32 %enable_pred, $4, 0; .reg .u32 %z; mov.u32 %z, 0; tcgen05.mma.cta_group::1.kind::f16 [$0], $1, $2, $3, {%z, %z, %z, %z}, %enable_pred; }", "r,l,l,r,r,~{memory}"(i32 %d, i64 %a, i64 %b, i32 %idesc, i1 %enable) #0
  ret void
}

attributes #0 = { convergent }
