; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.st.16x128b.x16; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_st_16x128b_x16_unpack16(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7, i32 %d8, i32 %d9, i32 %d10, i32 %d11, i32 %d12, i32 %d13, i32 %d14, i32 %d15, i32 %d16, i32 %d17, i32 %d18, i32 %d19, i32 %d20, i32 %d21, i32 %d22, i32 %d23, i32 %d24, i32 %d25, i32 %d26, i32 %d27, i32 %d28, i32 %d29, i32 %d30, i32 %d31) #0 {
  call void asm sideeffect "tcgen05.st.sync.aligned.16x128b.x16.unpack::16b.b32 [$0], {$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32};", "r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,r,~{memory}"(i32 %tmem, i32 %d0, i32 %d1, i32 %d2, i32 %d3, i32 %d4, i32 %d5, i32 %d6, i32 %d7, i32 %d8, i32 %d9, i32 %d10, i32 %d11, i32 %d12, i32 %d13, i32 %d14, i32 %d15, i32 %d16, i32 %d17, i32 %d18, i32 %d19, i32 %d20, i32 %d21, i32 %d22, i32 %d23, i32 %d24, i32 %d25, i32 %d26, i32 %d27, i32 %d28, i32 %d29, i32 %d30, i32 %d31) #0
  ret void
}

attributes #0 = { convergent }
