[package]
name = "dialect-iket"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Semantic IKET dialect for in-kernel event tracing"
readme = "README.md"

[dependencies]
pliron = { workspace = true }
pliron-derive = { workspace = true }
thiserror = { workspace = true }
linkme = { workspace = true }
combine = { workspace = true }
dyn-clone = { workspace = true }
