[package]
name = "iket-lower"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Lowering policy and runtime-compatible encoding for dialect-iket"
readme = "README.md"

[dependencies]
dialect-iket = { workspace = true }
pliron = { workspace = true }
thiserror = { workspace = true }
