/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `clc` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{
    clc::convert_generated_clc_query, clc::convert_generated_clc_try_cancel,
};
use dialect_nvvm::ops::{
    ClcQueryGetFirstCtaidXOp, ClcQueryGetFirstCtaidYOp, ClcQueryGetFirstCtaidZOp,
    ClcQueryIsCanceledOp, ClcTryCancelMulticastOp, ClcTryCancelOp,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for ClcQueryGetFirstCtaidXOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_clc_query(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm__nvvm_dclusterlaunchcontrol_dquery_ucancel_dget_ufirst_uctaid_dx",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ClcQueryGetFirstCtaidYOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_clc_query(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm__nvvm_dclusterlaunchcontrol_dquery_ucancel_dget_ufirst_uctaid_dy",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ClcQueryGetFirstCtaidZOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_clc_query(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm__nvvm_dclusterlaunchcontrol_dquery_ucancel_dget_ufirst_uctaid_dz",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ClcQueryIsCanceledOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_clc_query(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm__nvvm_dclusterlaunchcontrol_dquery_ucancel_dis_ucanceled",
            true,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ClcTryCancelOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_clc_try_cancel(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm__nvvm_dclusterlaunchcontrol_dtry_ucancel_dasync_dshared",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ClcTryCancelMulticastOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_clc_try_cancel(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm__nvvm_dclusterlaunchcontrol_dtry_ucancel_dasync_dmulticast_dshared",
        )
    }
}
