/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `cluster_barrier` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{common::call_intrinsic, common::inline_asm_convergent};
use crate::{IntrinsicBackend, context};
use dialect_nvvm::ops::{ClusterBarrierModeAttr, ClusterBarrierOp, ClusterSyncOp};
use llvm_export::types as llvm_types;
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::irbuild::rewriter::Rewriter;
use pliron::location::Located;
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for ClusterBarrierOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let recipe = match self.get_attr_nvvm_cluster_barrier_mode(ctx).as_deref() {
            Some(&ClusterBarrierModeAttr::Arrive) => (
                "llvm_nvvm_barrier_cluster_arrive",
                "barrier.cluster.arrive;",
            ),
            Some(&ClusterBarrierModeAttr::ArriveAligned) => (
                "llvm_nvvm_barrier_cluster_arrive_aligned",
                "barrier.cluster.arrive.aligned;",
            ),
            Some(&ClusterBarrierModeAttr::ArriveRelaxed) => (
                "llvm_nvvm_barrier_cluster_arrive_relaxed",
                "barrier.cluster.arrive.relaxed;",
            ),
            Some(&ClusterBarrierModeAttr::ArriveRelaxedAligned) => (
                "llvm_nvvm_barrier_cluster_arrive_relaxed_aligned",
                "barrier.cluster.arrive.relaxed.aligned;",
            ),
            Some(&ClusterBarrierModeAttr::Wait) => {
                ("llvm_nvvm_barrier_cluster_wait", "barrier.cluster.wait;")
            }
            Some(&ClusterBarrierModeAttr::WaitAligned) => (
                "llvm_nvvm_barrier_cluster_wait_aligned",
                "barrier.cluster.wait.aligned;",
            ),
            _ => {
                return pliron::input_err!(
                    self.get_operation().deref(ctx).loc(),
                    "nvvm.cluster_barrier mode has no generated lowering recipe",
                );
            }
        };
        let op = self.get_operation();
        let void_ty = llvm_types::VoidType::get(ctx);
        match context::lowering_options(ctx).intrinsic_backend {
            IntrinsicBackend::LlvmNvptx => {
                let function_ty = llvm_types::FuncType::get(ctx, void_ty.into(), vec![], false);
                call_intrinsic(ctx, rewriter, op, recipe.0, function_ty, vec![])?;
            }
            IntrinsicBackend::LibNvvm => {
                inline_asm_convergent(
                    ctx,
                    rewriter,
                    op,
                    void_ty.into(),
                    vec![],
                    recipe.1,
                    "~{memory}",
                );
            }
        }
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for ClusterSyncOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let void_ty = llvm_types::VoidType::get(ctx);
        match context::lowering_options(ctx).intrinsic_backend {
            IntrinsicBackend::LlvmNvptx => {
                let function_ty = llvm_types::FuncType::get(ctx, void_ty.into(), vec![], false);
                call_intrinsic(
                    ctx,
                    rewriter,
                    op,
                    "llvm_nvvm_barrier_cluster_arrive_aligned",
                    function_ty,
                    vec![],
                )?;
                call_intrinsic(
                    ctx,
                    rewriter,
                    op,
                    "llvm_nvvm_barrier_cluster_wait_aligned",
                    function_ty,
                    vec![],
                )?;
            }
            IntrinsicBackend::LibNvvm => {
                inline_asm_convergent(
                    ctx,
                    rewriter,
                    op,
                    void_ty.into(),
                    vec![],
                    "barrier.cluster.arrive.aligned; barrier.cluster.wait.aligned;",
                    "~{memory}",
                );
            }
        }
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}
