/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `integer_minmax` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::integer_minmax::convert_generated_integer_minmax;
use dialect_nvvm::ops::{
    MaxReluS16x2Op, MaxReluS32Op, MaxS16x2Op, MaxU16x2Op, MinReluS16x2Op, MinReluS32Op, MinS16x2Op,
    MinU16x2Op,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for MaxReluS16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "max.relu.s16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MaxReluS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "max.relu.s32")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MaxS16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "max.s16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MaxU16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "max.u16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MinReluS16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "min.relu.s16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MinReluS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "min.relu.s32")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MinS16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "min.s16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MinU16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_integer_minmax(ctx, rewriter, self.get_operation(), "min.u16x2")
    }
}
