/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `mbarrier_extended` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{
    common::cast_to_shared_addrspace, common::inline_asm_convergent, common::trunc_to_i1,
};
use dialect_nvvm::ops::{
    FenceMbarrierInitReleaseClusterOp, FenceProxyAsyncGenericAcquireSharedClusterClusterOp,
    FenceProxyAsyncGenericReleaseSharedCtaClusterOp, FenceProxyAsyncSharedCtaOp,
    MbarrierArriveClusterOp, MbarrierArriveExpectTxClusterOp, MbarrierArriveExpectTxSharedOp,
    MbarrierTryWaitParityClusterOp, MbarrierTryWaitParitySharedOp, MbarrierTryWaitSharedOp,
    NanosleepOp,
};
use llvm_export::types as llvm_types;
use pliron::builtin::types::{IntegerType, Signedness};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::irbuild::rewriter::Rewriter;
use pliron::op::Op;
use pliron::result::Result;
use pliron::value::DefiningEntity;

#[op_interface_impl]
impl MirToLlvmConversion for FenceMbarrierInitReleaseClusterOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let operands: Vec<_> = op.deref(ctx).operands().collect();
        if !operands.is_empty() {
            return pliron::input_err_noloc!(
                "fence_mbarrier_init_release_cluster requires 0 operands, got {}",
                operands.len()
            );
        }
        let void_ty = llvm_types::VoidType::get(ctx);
        inline_asm_convergent(
            ctx,
            rewriter,
            op,
            void_ty.into(),
            operands,
            "fence.mbarrier_init.release.cluster;",
            "~{memory}",
        );
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for FenceProxyAsyncGenericAcquireSharedClusterClusterOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let operands: Vec<_> = op.deref(ctx).operands().collect();
        if !operands.is_empty() {
            return pliron::input_err_noloc!(
                "fence_proxy_async_generic_acquire_shared_cluster_cluster requires 0 operands, got {}",
                operands.len()
            );
        }
        let void_ty = llvm_types::VoidType::get(ctx);
        inline_asm_convergent(
            ctx,
            rewriter,
            op,
            void_ty.into(),
            operands,
            "fence.proxy.async::generic.acquire.sync_restrict::shared::cluster.cluster;",
            "~{memory}",
        );
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for FenceProxyAsyncGenericReleaseSharedCtaClusterOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let operands: Vec<_> = op.deref(ctx).operands().collect();
        if !operands.is_empty() {
            return pliron::input_err_noloc!(
                "fence_proxy_async_generic_release_shared_cta_cluster requires 0 operands, got {}",
                operands.len()
            );
        }
        let void_ty = llvm_types::VoidType::get(ctx);
        inline_asm_convergent(
            ctx,
            rewriter,
            op,
            void_ty.into(),
            operands,
            "fence.proxy.async::generic.release.sync_restrict::shared::cta.cluster;",
            "~{memory}",
        );
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for FenceProxyAsyncSharedCtaOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let operands: Vec<_> = op.deref(ctx).operands().collect();
        if !operands.is_empty() {
            return pliron::input_err_noloc!(
                "fence_proxy_async_shared_cta requires 0 operands, got {}",
                operands.len()
            );
        }
        let void_ty = llvm_types::VoidType::get(ctx);
        inline_asm_convergent(
            ctx,
            rewriter,
            op,
            void_ty.into(),
            operands,
            "fence.proxy.async.shared::cta;",
            "~{memory}",
        );
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MbarrierArriveClusterOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 1 {
            return pliron::input_err_noloc!(
                "mbarrier_arrive_cluster requires 1 operands, got {}",
                operands.len()
            );
        }
        let void_ty = llvm_types::VoidType::get(ctx);
        inline_asm_convergent(
            ctx,
            rewriter,
            op,
            void_ty.into(),
            operands,
            "mbarrier.arrive.release.cluster.shared::cluster.b64 _, [$0];",
            "l,~{memory}",
        );
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MbarrierArriveExpectTxSharedOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let mut operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 2 {
            return pliron::input_err_noloc!(
                "mbarrier_arrive_expect_tx requires 2 operands, got {}",
                operands.len()
            );
        }
        operands[0] = cast_to_shared_addrspace(ctx, rewriter, operands[0]);
        let result_ty = IntegerType::get(ctx, 64, Signedness::Signless);
        let asm = inline_asm_convergent(
            ctx,
            rewriter,
            op,
            result_ty.into(),
            operands,
            "mbarrier.arrive.expect_tx.release.cta.shared::cta.b64 $0, [$1], $2;",
            "=l,l,r,~{memory}",
        );
        rewriter.replace_operation(ctx, op, asm);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MbarrierArriveExpectTxClusterOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let mut operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 2 {
            return pliron::input_err_noloc!(
                "mbarrier_arrive_expect_tx_cluster requires 2 operands, got {}",
                operands.len()
            );
        }
        operands[0] = cast_to_shared_addrspace(ctx, rewriter, operands[0]);
        let result_ty = IntegerType::get(ctx, 64, Signedness::Signless);
        let asm = inline_asm_convergent(
            ctx,
            rewriter,
            op,
            result_ty.into(),
            operands,
            "mbarrier.arrive.expect_tx.relaxed.cluster.shared::cta.b64 $0, [$1], $2;",
            "=l,l,r,~{memory}",
        );
        rewriter.replace_operation(ctx, op, asm);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MbarrierTryWaitSharedOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let mut operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 2 {
            return pliron::input_err_noloc!(
                "mbarrier_try_wait requires 2 operands, got {}",
                operands.len()
            );
        }
        operands[0] = cast_to_shared_addrspace(ctx, rewriter, operands[0]);
        let result_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        let asm = inline_asm_convergent(
            ctx,
            rewriter,
            op,
            result_ty.into(),
            operands,
            "{ .reg .pred %p0; mbarrier.try_wait.shared.b64 %p0, [$1], $2; selp.b32 $0, 1, 0, %p0; }",
            "=r,l,l,~{memory}",
        );
        let asm_result = asm.deref(ctx).get_result(0);
        let result = trunc_to_i1(ctx, rewriter, asm_result);
        let DefiningEntity::Op(result_op) = result.defining_entity() else {
            unreachable!()
        };
        rewriter.replace_operation(ctx, op, result_op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MbarrierTryWaitParitySharedOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let mut operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 2 {
            return pliron::input_err_noloc!(
                "mbarrier_try_wait_parity requires 2 operands, got {}",
                operands.len()
            );
        }
        operands[0] = cast_to_shared_addrspace(ctx, rewriter, operands[0]);
        let result_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        let asm = inline_asm_convergent(
            ctx,
            rewriter,
            op,
            result_ty.into(),
            operands,
            "{ .reg .pred %p0; mbarrier.try_wait.parity.shared::cta.b64 %p0, [$1], $2; selp.b32 $0, 1, 0, %p0; }",
            "=r,l,r,~{memory}",
        );
        let asm_result = asm.deref(ctx).get_result(0);
        let result = trunc_to_i1(ctx, rewriter, asm_result);
        let DefiningEntity::Op(result_op) = result.defining_entity() else {
            unreachable!()
        };
        rewriter.replace_operation(ctx, op, result_op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MbarrierTryWaitParityClusterOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let mut operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 2 {
            return pliron::input_err_noloc!(
                "mbarrier_try_wait_parity_cluster requires 2 operands, got {}",
                operands.len()
            );
        }
        operands[0] = cast_to_shared_addrspace(ctx, rewriter, operands[0]);
        let result_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        let asm = inline_asm_convergent(
            ctx,
            rewriter,
            op,
            result_ty.into(),
            operands,
            "{ .reg .pred %p0; mbarrier.try_wait.parity.acquire.cluster.shared::cta.b64 %p0, [$1], $2; selp.b32 $0, 1, 0, %p0; }",
            "=r,l,r,~{memory}",
        );
        let asm_result = asm.deref(ctx).get_result(0);
        let result = trunc_to_i1(ctx, rewriter, asm_result);
        let DefiningEntity::Op(result_op) = result.defining_entity() else {
            unreachable!()
        };
        rewriter.replace_operation(ctx, op, result_op);
        Ok(())
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for NanosleepOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 1 {
            return pliron::input_err_noloc!(
                "nanosleep requires 1 operands, got {}",
                operands.len()
            );
        }
        let void_ty = llvm_types::VoidType::get(ctx);
        inline_asm_convergent(
            ctx,
            rewriter,
            op,
            void_ty.into(),
            operands,
            "nanosleep.u32 $0;",
            "r,~{memory}",
        );
        rewriter.erase_operation(ctx, op);
        Ok(())
    }
}
