/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `packed_atomic` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::atomic::convert_packed_atom_add;
use dialect_nvvm::ops::{
    NvvmAtomAddBf16x2Op, NvvmAtomAddF16x2Op, PackedAtomicAddOp, PackedAtomicAtomicityAttr,
    PackedAtomicFormatAttr, PackedAtomicOrderingAttr, PackedAtomicRoundingAttr,
    PackedAtomicScopeAttr, PackedAtomicStateSpaceAttr, PackedAtomicSubnormalAttr,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::location::Located;
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for PackedAtomicAddOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let format = self.get_attr_nvvm_packed_atomic_format(ctx);
        let state_space = self.get_attr_nvvm_packed_atomic_state_space(ctx);
        let ordering = self.get_attr_nvvm_packed_atomic_ordering(ctx);
        let scope = self.get_attr_nvvm_packed_atomic_scope(ctx);
        let rounding = self.get_attr_nvvm_packed_atomic_rounding(ctx);
        let subnormal = self.get_attr_nvvm_packed_atomic_subnormal(ctx);
        let atomicity = self.get_attr_nvvm_packed_atomic_atomicity(ctx);
        let ptx_type = match (
            format.as_deref(),
            state_space.as_deref(),
            ordering.as_deref(),
            scope.as_deref(),
            rounding.as_deref(),
            subnormal.as_deref(),
            atomicity.as_deref(),
        ) {
            (
                Some(&PackedAtomicFormatAttr::F16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "f16x2",
            (
                Some(&PackedAtomicFormatAttr::Bf16x2),
                Some(&PackedAtomicStateSpaceAttr::Global),
                Some(&PackedAtomicOrderingAttr::Relaxed),
                Some(&PackedAtomicScopeAttr::Gpu),
                Some(&PackedAtomicRoundingAttr::Rn),
                Some(&PackedAtomicSubnormalAttr::NoFtz),
                Some(&PackedAtomicAtomicityAttr::PerElement),
            ) => "bf16x2",
            _ => {
                return pliron::input_err!(
                    self.get_operation().deref(ctx).loc(),
                    "nvvm.packed_atomic_add attributes have no generated lowering recipe",
                );
            }
        };
        drop((
            format,
            state_space,
            ordering,
            scope,
            rounding,
            subnormal,
            atomicity,
        ));
        convert_packed_atom_add(ctx, rewriter, self.get_operation(), ptx_type)
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for NvvmAtomAddF16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_packed_atom_add(ctx, rewriter, self.get_operation(), "f16x2")
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for NvvmAtomAddBf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_packed_atom_add(ctx, rewriter, self.get_operation(), "bf16x2")
    }
}
