/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `packed_conversion` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{
    packed::convert_generated_packed_f32x2, packed::convert_generated_packed_unary,
};
use dialect_nvvm::ops::{
    CvtF16x2F32Op, CvtF32x2Bf16x2Op, CvtRnF16x2E4m3x2Op, CvtRnF16x2E5m2x2Op, CvtRnReluBf16x2F32Op,
    CvtRnReluF16x2E4m3x2Op, CvtRnReluF16x2E5m2x2Op, CvtRnReluF16x2F32Op,
    CvtRnSatfiniteE4m3x2F16x2Op, CvtRnSatfiniteE4m3x2F32Op, CvtRnSatfiniteE5m2x2F16x2Op,
    CvtRnSatfiniteE5m2x2F32Op, CvtRnSatfiniteReluE4m3x2F16x2Op, CvtRnSatfiniteReluE4m3x2F32Op,
    CvtRnSatfiniteReluE5m2x2F16x2Op, CvtRnSatfiniteReluE5m2x2F32Op, CvtRzBf16x2F32Op,
    CvtRzF16x2F32Op,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for CvtF16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            None,
            "cvt.rn.f16x2.f32",
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtF32x2Bf16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            None,
            "cvt.rn.bf16x2.f32",
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnF16x2E4m3x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.f16x2.e4m3x2",
            32,
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnF16x2E5m2x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.f16x2.e5m2x2",
            32,
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnReluBf16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            None,
            "cvt.rn.relu.bf16x2.f32",
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnReluF16x2E4m3x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.relu.f16x2.e4m3x2",
            32,
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnReluF16x2E5m2x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.relu.f16x2.e5m2x2",
            32,
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnReluF16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            None,
            "cvt.rn.relu.f16x2.f32",
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteE4m3x2F16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.satfinite.e4m3x2.f16x2",
            16,
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteE4m3x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            Some("llvm_nvvm_ff_to_e4m3x2_rn"),
            "cvt.rn.satfinite.e4m3x2.f32",
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteE5m2x2F16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.satfinite.e5m2x2.f16x2",
            16,
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteE5m2x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            Some("llvm_nvvm_ff_to_e5m2x2_rn"),
            "cvt.rn.satfinite.e5m2x2.f32",
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteReluE4m3x2F16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.satfinite.relu.e4m3x2.f16x2",
            16,
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteReluE4m3x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            Some("llvm_nvvm_ff_to_e4m3x2_rn_relu"),
            "cvt.rn.satfinite.relu.e4m3x2.f32",
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteReluE5m2x2F16x2Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_unary(
            ctx,
            rewriter,
            self.get_operation(),
            "cvt.rn.satfinite.relu.e5m2x2.f16x2",
            16,
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRnSatfiniteReluE5m2x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            Some("llvm_nvvm_ff_to_e5m2x2_rn_relu"),
            "cvt.rn.satfinite.relu.e5m2x2.f32",
            16,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRzBf16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            None,
            "cvt.rz.bf16x2.f32",
            32,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CvtRzF16x2F32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_packed_f32x2(
            ctx,
            rewriter,
            self.get_operation(),
            None,
            "cvt.rz.f16x2.f32",
            32,
        )
    }
}
