/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `scalar_arithmetic` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::scalar_arithmetic::convert_generated_scalar_arithmetic;
use dialect_nvvm::ops::{
    ScalarArithmeticFormatAttr, ScalarArithmeticOp, ScalarArithmeticOperationAttr,
    ScalarArithmeticRoundingAttr, ScalarArithmeticSaturationAttr, ScalarArithmeticSubnormalAttr,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::location::Located;
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for ScalarArithmeticOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let recipe = match (
            self.get_attr_nvvm_scalar_arithmetic_format(ctx).as_deref(),
            self.get_attr_nvvm_scalar_arithmetic_operation(ctx)
                .as_deref(),
            self.get_attr_nvvm_scalar_arithmetic_rounding(ctx)
                .as_deref(),
            self.get_attr_nvvm_scalar_arithmetic_subnormal(ctx)
                .as_deref(),
            self.get_attr_nvvm_scalar_arithmetic_saturation(ctx)
                .as_deref(),
        ) {
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rm_f", "add.rm.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rm_d", "add.rm.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rm_ftz_f", "add.rm.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_add_rm_ftz_sat_f",
                "add.rm.sat.ftz.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_add_rm_sat_f", "add.rm.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rn_f", "add.rn.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rn_d", "add.rn.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rn_ftz_f", "add.rn.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_add_rn_ftz_sat_f",
                "add.rn.sat.ftz.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_add_rn_sat_f", "add.rn.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rp_f", "add.rp.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rp_d", "add.rp.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rp_ftz_f", "add.rp.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_add_rp_ftz_sat_f",
                "add.rp.sat.ftz.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_add_rp_sat_f", "add.rp.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rz_f", "add.rz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rz_d", "add.rz.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_add_rz_ftz_f", "add.rz.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_add_rz_ftz_sat_f",
                "add.rz.sat.ftz.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Add),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_add_rz_sat_f", "add.rz.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rm_f", "div.rm.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rm_d", "div.rm.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rm_ftz_f", "div.rm.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rn_f", "div.rn.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rn_d", "div.rn.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rn_ftz_f", "div.rn.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rp_f", "div.rp.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rp_d", "div.rp.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rp_ftz_f", "div.rp.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rz_f", "div.rz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rz_d", "div.rz.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Div),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_div_rz_ftz_f", "div.rz.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rm_f", "fma.rm.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rm_d", "fma.rm.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rm_ftz_f", "fma.rm.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_fma_rm_ftz_sat_f",
                "fma.rm.ftz.sat.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_fma_rm_sat_f", "fma.rm.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rn_f", "fma.rn.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rn_d", "fma.rn.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rn_ftz_f", "fma.rn.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_fma_rn_ftz_sat_f",
                "fma.rn.ftz.sat.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_fma_rn_sat_f", "fma.rn.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rp_f", "fma.rp.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rp_d", "fma.rp.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rp_ftz_f", "fma.rp.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_fma_rp_ftz_sat_f",
                "fma.rp.ftz.sat.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_fma_rp_sat_f", "fma.rp.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rz_f", "fma.rz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rz_d", "fma.rz.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_fma_rz_ftz_f", "fma.rz.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => (
                "llvm_nvvm_fma_rz_ftz_sat_f",
                "fma.rz.ftz.sat.f32",
                false,
                true,
            ),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Fma),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::Sat),
            ) => ("llvm_nvvm_fma_rz_sat_f", "fma.rz.sat.f32", false, true),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rm_f", "mul.rm.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rm_d", "mul.rm.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rm),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rm_ftz_f", "mul.rm.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rn_f", "mul.rn.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rn_d", "mul.rn.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rn),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rn_ftz_f", "mul.rn.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rp_f", "mul.rp.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rp_d", "mul.rp.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rp),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rp_ftz_f", "mul.rp.ftz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rz_f", "mul.rz.f32", false, false),
            (
                Some(&ScalarArithmeticFormatAttr::F64),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Preserve),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rz_d", "mul.rz.f64", true, false),
            (
                Some(&ScalarArithmeticFormatAttr::F32),
                Some(&ScalarArithmeticOperationAttr::Mul),
                Some(&ScalarArithmeticRoundingAttr::Rz),
                Some(&ScalarArithmeticSubnormalAttr::Ftz),
                Some(&ScalarArithmeticSaturationAttr::None),
            ) => ("llvm_nvvm_mul_rz_ftz_f", "mul.rz.ftz.f32", false, false),
            _ => {
                return pliron::input_err!(
                    self.get_operation().deref(ctx).loc(),
                    "nvvm.scalar_arithmetic variant has no generated lowering recipe",
                );
            }
        };
        convert_generated_scalar_arithmetic(
            ctx,
            rewriter,
            self.get_operation(),
            recipe.0,
            recipe.1,
            recipe.2,
            recipe.3,
        )
    }
}
