/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 016c9d9b55b84d99d56fe2690dce4b3ba7ded5318890996a7459a142ddb5edf7.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `wgmma_control` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{common::call_intrinsic, common::inline_asm_convergent};
use crate::{IntrinsicBackend, context};
use dialect_nvvm::ops::{
    WgmmaCommitGroupSyncAlignedOp, WgmmaFenceSyncAlignedOp, WgmmaWaitGroupSyncAlignedOp,
};
use llvm_export::types as llvm_types;
use pliron::builtin::types::{IntegerType, Signedness};
use pliron::context::{Context, Ptr};
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::irbuild::rewriter::Rewriter;
use pliron::location::Located;
use pliron::op::Op;
use pliron::operation::Operation;
use pliron::result::Result;

fn convert_generated_wgmma_control(
    ctx: &mut Context,
    rewriter: &mut DialectConversionRewriter,
    op: Ptr<Operation>,
    intrinsic_name: &str,
    ptx: &str,
    has_immediate: bool,
) -> Result<()> {
    let operands: Vec<_> = op.deref(ctx).operands().collect();
    if operands.len() != usize::from(has_immediate) {
        return pliron::input_err!(
            op.deref(ctx).loc(),
            "generated WGMMA control has the wrong operand count",
        );
    }
    let void_ty = llvm_types::VoidType::get(ctx);
    match context::lowering_options(ctx).intrinsic_backend {
        IntrinsicBackend::LlvmNvptx => {
            let arguments = if has_immediate {
                vec![IntegerType::get(ctx, 64, Signedness::Signless).into()]
            } else {
                vec![]
            };
            let function_ty = llvm_types::FuncType::get(ctx, void_ty.into(), arguments, false);
            call_intrinsic(ctx, rewriter, op, intrinsic_name, function_ty, operands)?;
        }
        IntrinsicBackend::LibNvvm => {
            let constraints = if has_immediate {
                "n,~{memory}"
            } else {
                "~{memory}"
            };
            inline_asm_convergent(
                ctx,
                rewriter,
                op,
                void_ty.into(),
                operands,
                ptx,
                constraints,
            );
        }
    }
    rewriter.erase_operation(ctx, op);
    Ok(())
}

#[op_interface_impl]
impl MirToLlvmConversion for WgmmaCommitGroupSyncAlignedOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_wgmma_control(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm__nvvm_dwgmma_dcommit_ugroup_dsync_daligned",
            "wgmma.commit_group.sync.aligned;",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for WgmmaFenceSyncAlignedOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_wgmma_control(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_wgmma_fence_sync_aligned",
            "wgmma.fence.sync.aligned;",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for WgmmaWaitGroupSyncAlignedOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_wgmma_control(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm__nvvm_dwgmma_dwait_ugroup_dsync_daligned",
            "wgmma.wait_group.sync.aligned $0;",
            true,
        )
    }
}
